### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by julianD77** [RobK/photobox-downloader#2]
Hi, has anyone ever come across this access denied screen when using the photobox-downloader script?

Im guessing it may just be Photobox security policies blocking the direct image download.

Any ideas to get around this?

Thanks

Julian

![image](https://cloud.githubusercontent.com/assets/15604826/17350783/867e48a0-5921-11e6-8480-cf8f5e78ac84.png)

**Comment by RobK** [comment]
Hi, sorry for the delay in replying. This is caused because of recent changes in photobox, they are now temporarily banning (5 min bans) for people who make too many requests.

I have updated photobox-downloader to rate limit the downloads (slower, but avoids any temporary ban issues).
Also added a resume feature (to skip already downloaded files)
Improved the debugging

If you update (run `npm update -g photobox-downloader`) and try again it should work fine now.

**Comment by RobK** [comment]
No follow up, closing issue
